### ISSUE TITLE
How to revert the changes of dns agent?

### ISSUE THREAD

**Issue by hinogi** [jacob-pro/wsl2-dns-agent#12]
How can I let WSL2 generate the resolv.conf again?

**Comment by jacob-pro** [comment]
Hi @hinogi 

The main change is this option: `generateResolvConf` in `/etc/wsl.conf`, you need to revert this to true.

https://learn.microsoft.com/en-us/windows/wsl/wsl-config#network-settings

For reference this is the changes this tool makes:

https://github.com/jacob-pro/wsl2-dns-agent/blob/74e9723bb0a8699e02dd4625faf26bdc1a83dc23/src/runner.rs#L111-L127

**Comment by hinogi** [comment]
thx
