### ISSUE TITLE
Having to Manually Set InterfaceMetric

### ISSUE THREAD

**Issue by Shackelford-Arden** [jacob-pro/wsl2-dns-agent#3]
First off, big thanks to you for putting together this little helper agent, it has saved me a great deal of headache :smile:

Anyway, I was curious if you could provide some insight with something that I'm seeing.

When I connect to the VPN (Cisco AnyConnect), WSL's /etc/resolv.conf gets updated correctly, but resolution continues to fail.

Looking at the output of this command:

```powershell
Get-NetIPInterface | Where-Object {$_.ConnectionState -eq 'Connected'} | Sort-Object -Property InterfaceMetric
```

I see this (truncated for brevity):

```plaintext
ifIndex InterfaceAlias                  AddressFamily NlMtu(Bytes) InterfaceMetric Dhcp     ConnectionState PolicyStore
------- --------------                  ------------- ------------ --------------- ----     --------------- -----------
5       Ethernet 2                      IPv4                  1390               1 Disabled Connected       ActiveStore
5       Ethernet 2                      IPv6                  1390            6000 Enabled  Connected       ActiveStore
```

Note the `Ethernet 2` interface at the top of the list has an `InterfaceMetric` of `1` instead of `6000`. Previously I did set the value here to `6000` (as indicated by the second entry). Now it seems that I need to come back in each time and run the command you'd provided in your documentation:

```powershell
Set-NetIPInterface -InterfaceAlias "Ethernet 2" -InterfaceMetric 6000
```

Once I do this manually, things continue to work wonderfully. 

I was under the impression that the agent would watch for this and handle it, but I figured I'd check and see if that understanding was correct or if I misunderstood and it's simply a fact of life that I'll need to do this manually (which at least gets me a working session, which I'm glad to have!)

**Comment by jacob-pro** [comment]
Hi @Shackelford-Arden 

I take it the above "Ethernet 2" is the Cisco AnyConnect VPN adapter ?

In which case did you [read the guide linked in the README](https://github.com/jacob-pro/wsl2-dns-agent/blob/master/docs/ROUTING.md) ?

> but resolution continues to fail.

It isn't resolution that is the issue - it is connectivity full stop, e.g. try running the following command with the IP address of your DNS server, or Google etc.

```bash
nc -zvu $DNS_IPV4 53
```

You will find that WSL is not able to route to the internet at all (as per step 1 in the guide).

> Now it seems that I need to come back in each time and run the command you'd provided in your documentation:

Step 2 of the guide provides instructions to automate this command using task scheduler. 

I would like to incorporate it into this tool, but I can't see any straightforward way of doing it that command requires administrator privileges / elevation - which wouldn't work nicely with a tray application - it would require displaying the UAC prompt every time or at startup.

**Comment by Shackelford-Arden** [comment]
My goodness lol. I totally managed to completely forget/block out the scheduled task bit. 

Thank you for your patience! The reasoning you have makes sense. 

Hope you have a great day! And thanks again for this 😎 Serious sanity gained with this.
