### ISSUE TITLE
[QUESTION] How can we disable an IPv6-DNS response at all?

### ISSUE THREAD

**Issue by PeterCodar** [jacob-pro/wsl2-dns-agent#5]
In your example with 1 Ethernet-Adapater:
https://github.com/jacob-pro/wsl2-dns-agent/blob/master/docs/DNS_PRIORITY.md#dns-servers-on-the-same-interface

How would you prevent that you get an IPv6-Response at all?
If you are in a situation where it is necessary to only get an IPv4, how can we disable the IPv6-DNS at all?

**Comment by jacob-pro** [comment]
Either remove the IPv6 DNS server from the network adapter - or disable the IPv6 stack on that network adapter.

**Comment by jacob-pro** [comment]
To be honest this is kind of out of scope for this project - the goal of that document was just to discover how Windows works. 

The ws2-dns-agent tool itself filters out any IPv6 servers regardless:

https://github.com/jacob-pro/wsl2-dns-agent/blob/1d83b43f479ed01a68b181c5f6d93fbbbec6d49f/src/dns.rs#L211-L218

**Comment by PeterCodar** [comment]
Ups, sorry for going out of scope...
