### ISSUE TITLE
Rare crash: panicked at Result::unwrap(), Error { code: 0x800705B4, message: This operation returned because the timeout period expired. } at src/tray.rs:191:56

### ISSUE THREAD

**Issue by theo543** [jacob-pro/wsl2-dns-agent#9]
I'm not sure, but I think this happens when waking up from sleep and/or hibernation.
![super_rare_error](https://github.com/jacob-pro/wsl2-dns-agent/assets/81699222/6200f2ff-ac84-444e-8627-f0a5148c644a)

**Comment by jacob-pro** [comment]
that error seems to be coming from here:
https://github.com/jacob-pro/wsl2-dns-agent/blob/79c56ccb4be6f285144a20dde8b599bc6dd6ad62/src/tray.rs#L191

I'm not sure why this is failing, but showing a notification isn't very critical, so I can change it to silently continue instead of exiting

**Comment by jacob-pro** [comment]
Version [v0.3.6](https://github.com/jacob-pro/wsl2-dns-agent/releases/tag/v0.3.6) should no longer crash when this happens
